# Generated by Django 5.0.3 on 2024-03-17 14:41
from django.db import migrations
from quickstart.models import CityWeather

def seed_data(apps, schema_editor):
        CityWeather.objects.create(city_name='new_york', temperature=1.5, humidity=60, wind_speed=10.5, condition='Sunny', date='2024-01-1')
        CityWeather.objects.create(city_name='new_york', temperature=2.5, humidity=60, wind_speed=10.5, condition='Sunny', date='2024-01-2')
        CityWeather.objects.create(city_name='new_york', temperature=0.5, humidity=60, wind_speed=10.5, condition='Sunny', date='2024-01-3')
        CityWeather.objects.create(city_name='new_york', temperature=0.0, humidity=60, wind_speed=10.5, condition='Cloudy', date='2024-01-4')
        CityWeather.objects.create(city_name='new_york', temperature=-1, humidity=60, wind_speed=10.5, condition='Snowing', date='2024-01-5')
        CityWeather.objects.create(city_name='new_york', temperature=2.5, humidity=60, wind_speed=10.5, condition='Snowing', date='2024-01-6')
        CityWeather.objects.create(city_name='london', temperature=1.0, humidity=60, wind_speed=10.5, condition='Sunny', date='2024-01-1')
        CityWeather.objects.create(city_name='london', temperature=2.5, humidity=60, wind_speed=10.5, condition='Cloudy', date='2024-01-2')
        CityWeather.objects.create(city_name='london', temperature=0.0, humidity=60, wind_speed=10.5, condition='Cloudy', date='2024-01-3')
        CityWeather.objects.create(city_name='london', temperature=1.0, humidity=60, wind_speed=10.5, condition='Cloudy', date='2024-01-4')
        CityWeather.objects.create(city_name='london', temperature=5.5, humidity=60, wind_speed=10.5, condition='Cloudy', date='2024-01-5')
        CityWeather.objects.create(city_name='london', temperature=2.5, humidity=60, wind_speed=10.5, condition='Cloudy', date='2024-01-6')



class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
    ]
